import type { TenseData } from './types';

export const TENSE_CATEGORIES: TenseData[] = [
  {
    id: 'present',
    number: 1,
    category: 'Present',
    title: 'Present Tenses',
    structure: 'Simple · Continuous · Perfect · Perfect Continuous',
    explanation: 'Habits, ongoing actions, and timeless truths.',
    example: 'The sun rises over Kyoto every morning.',
    image: 'https://picsum.photos/seed/tense-sunrise-kyoto/900/1100',
    imageAlt: 'Sunrise light over traditional rooftops',
  },
  {
    id: 'past',
    number: 2,
    category: 'Past',
    title: 'Past Tenses',
    structure: 'Simple · Continuous · Perfect · Perfect Continuous',
    explanation: 'Stories and events already completed.',
    example: 'The train departed Lisbon at dawn.',
    image: 'https://picsum.photos/seed/tense-vintage-archive/900/1100',
    imageAlt: 'Vintage train station archive photograph',
  },
  {
    id: 'future',
    number: 3,
    category: 'Future',
    title: 'Future Tenses',
    structure: 'Simple · Continuous · Perfect · Perfect Continuous',
    explanation: "Plans, predictions, and what's to come.",
    example: 'We will land in Reykjavik just after midnight.',
    image: 'https://picsum.photos/seed/tense-plane-horizon/900/1100',
    imageAlt: 'View from a plane window over an open horizon',
  },
  {
    id: 'future-in-the-past',
    number: 4,
    category: 'Future in the Past',
    title: 'Past Future Tenses',
    structure: 'Simple · Continuous · Perfect · Perfect Continuous',
    explanation: 'The future seen from a moment in the past.',
    example: 'He said the last train would leave at eleven.',
    image: 'https://picsum.photos/seed/tense-station-clock/900/1100',
    imageAlt: 'An old station clock above an empty platform',
  },
];