import type { TenseData } from './types';

/**
 * NOTE ON IMAGES
 * These use picsum.photos seeded placeholders so the section renders
 * reliably out of the box. Swap `image` for your own curated cultural
 * photography (Unsplash+/your CMS) before shipping — each seed below
 * was chosen to loosely match the mood of its tense (sunrise for the
 * "always true" Present Simple, motion blur for continuous forms, etc.)
 * so keep that pairing in mind when you replace them.
 */
export const TENSES: TenseData[] = [
  {
    id: 'present-simple',
    number: 1,
    category: 'Present',
    title: 'Present Simple',
    structure: 'Subject + V1 / V(s)',
    explanation:
      'Facts, habits and truths that hold regardless of when you look at the clock.',
    example: 'The sun rises over Kyoto every morning.',
    image: 'https://picsum.photos/seed/tense-sunrise-kyoto/900/1100',
    imageAlt: 'Sunrise light over traditional rooftops',
  },
  {
    id: 'present-continuous',
    number: 2,
    category: 'Present',
    title: 'Present Continuous',
    structure: 'Subject + am/is/are + V-ing',
    explanation:
      'Something unfolding right now, mid-motion, not yet finished.',
    example: 'The crowd is crossing Shibuya as the lights change.',
    image: 'https://picsum.photos/seed/tense-shibuya-motion/900/1100',
    imageAlt: 'Motion-blurred crowd crossing a city intersection',
  },
  {
    id: 'present-perfect',
    number: 3,
    category: 'Present',
    title: 'Present Perfect',
    structure: 'Subject + have/has + V3',
    explanation:
      'A past action whose result still matters right now — the bridge between then and today.',
    example: 'She has restored the old fresco by hand.',
    image: 'https://picsum.photos/seed/tense-restoration-hands/900/1100',
    imageAlt: 'Hands carefully restoring an old painting',
  },
  {
    id: 'present-perfect-continuous',
    number: 4,
    category: 'Present',
    title: 'Present Perfect Continuous',
    structure: 'Subject + have/has been + V-ing',
    explanation:
      'An effort that started earlier and is still running, with the strain still visible.',
    example: 'The potter has been shaping this bowl for an hour.',
    image: 'https://picsum.photos/seed/tense-potter-wheel/900/1100',
    imageAlt: 'Long exposure of a potter working at a wheel',
  },
  {
    id: 'past-simple',
    number: 5,
    category: 'Past',
    title: 'Past Simple',
    structure: 'Subject + V2',
    explanation: 'A completed moment, closed and dated, like a photograph in an archive.',
    example: 'The train departed Lisbon at dawn.',
    image: 'https://picsum.photos/seed/tense-vintage-archive/900/1100',
    imageAlt: 'Vintage train station archive photograph',
  },
  {
    id: 'past-continuous',
    number: 6,
    category: 'Past',
    title: 'Past Continuous',
    structure: 'Subject + was/were + V-ing',
    explanation: 'A scene already in progress when something else cut through it.',
    example: 'Rain was falling when the market closed for the night.',
    image: 'https://picsum.photos/seed/tense-rain-window/900/1100',
    imageAlt: 'Rain streaking down a market stall window at night',
  },
  {
    id: 'past-perfect',
    number: 7,
    category: 'Past',
    title: 'Past Perfect',
    structure: 'Subject + had + V3',
    explanation: 'The past before the past — one layer further back in time.',
    example: 'The city had rebuilt its walls long before the war began.',
    image: 'https://picsum.photos/seed/tense-ancient-ruins/900/1100',
    imageAlt: 'Layered stone ruins suggesting deep history',
  },
  {
    id: 'past-perfect-continuous',
    number: 8,
    category: 'Past',
    title: 'Past Perfect Continuous',
    structure: 'Subject + had been + V-ing',
    explanation: 'A stretch of time that had already been running before an earlier event.',
    example: 'They had been walking for days before they saw the coastline.',
    image: 'https://picsum.photos/seed/tense-long-road-dusk/900/1100',
    imageAlt: 'A long road stretching toward the horizon at dusk',
  },
  {
    id: 'future-simple',
    number: 9,
    category: 'Future',
    title: 'Future Simple',
    structure: 'Subject + will + V1',
    explanation: 'A decision, promise or prediction cast forward from this moment.',
    example: 'We will land in Reykjavik just after midnight.',
    image: 'https://picsum.photos/seed/tense-plane-horizon/900/1100',
    imageAlt: 'View from a plane window over an open horizon',
  },
  {
    id: 'future-continuous',
    number: 10,
    category: 'Future',
    title: 'Future Continuous',
    structure: 'Subject + will be + V-ing',
    explanation: 'Something that will already be in motion at a specific point ahead.',
    example: 'This time tomorrow, the city will be lighting up for the festival.',
    image: 'https://picsum.photos/seed/tense-city-lights-night/900/1100',
    imageAlt: 'City lights beginning to glow at dusk',
  },
  {
    id: 'future-perfect',
    number: 11,
    category: 'Future',
    title: 'Future Perfect',
    structure: 'Subject + will have + V3',
    explanation: 'Looking back from a future point at something that will already be finished.',
    example: 'By sunrise, they will have reached the summit.',
    image: 'https://picsum.photos/seed/tense-mountain-summit/900/1100',
    imageAlt: 'Climbers near a mountain summit at first light',
  },
  {
    id: 'future-perfect-continuous',
    number: 12,
    category: 'Future',
    title: 'Future Perfect Continuous',
    structure: 'Subject + will have been + V-ing',
    explanation: 'A duration that will have been running continuously by a future deadline.',
    example: 'By mile twenty, she will have been running for three hours.',
    image: 'https://picsum.photos/seed/tense-marathon-runner/900/1100',
    imageAlt: 'A runner mid-stride during a long-distance race',
  },
  {
    id: 'future-in-the-past-simple',
    number: 13,
    category: 'Future in the Past',
    title: 'Future in the Past Simple',
    structure: 'Subject + would + V1',
    explanation: 'A future imagined from a moment that is now itself in the past.',
    example: 'He said the last train would leave at eleven.',
    image: 'https://picsum.photos/seed/tense-station-clock/900/1100',
    imageAlt: 'An old station clock above an empty platform',
  },
  {
    id: 'future-in-the-past-continuous',
    number: 14,
    category: 'Future in the Past',
    title: 'Future in the Past Continuous',
    structure: 'Subject + would be + V-ing',
    explanation: 'An action expected, back then, to be mid-way through at a later point.',
    example: 'She knew that by evening, they would be crossing the border.',
    image: 'https://picsum.photos/seed/tense-train-window-journey/900/1100',
    imageAlt: 'View from a train window during a journey at dusk',
  },
  {
    id: 'future-in-the-past-perfect',
    number: 15,
    category: 'Future in the Past',
    title: 'Future in the Past Perfect',
    structure: 'Subject + would have + V3',
    explanation: 'A completion once expected, seen from a viewpoint that has since moved past it.',
    example: 'They believed the bridge would have been finished by spring.',
    image: 'https://picsum.photos/seed/tense-unfinished-bridge/900/1100',
    imageAlt: 'An unfinished bridge structure against the sky',
  },
  {
    id: 'future-in-the-past-perfect-continuous',
    number: 16,
    category: 'Future in the Past',
    title: 'Future in the Past Perfect Continuous',
    structure: 'Subject + would have been + V-ing',
    explanation: 'A duration once imagined as still unfolding by some later, now-passed point.',
    example: 'He thought that by now, the tide would have been rising for hours.',
    image: 'https://picsum.photos/seed/tense-fading-light-water/900/1100',
    imageAlt: 'Fading light over still water at the shoreline',
  },
];
