/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TensesRouteImport } from './routes/tenses'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as CeritaRouteImport } from './routes/cerita'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TensesTenseRouteImport } from './routes/tenses_.$tense'
import { Route as QuizQuizIdRouteImport } from './routes/quiz_.$quizId'
import { Route as CeritaSlugRouteImport } from './routes/cerita_.$slug'

const TensesRoute = TensesRouteImport.update({
  id: '/tenses',
  path: '/tenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CeritaRoute = CeritaRouteImport.update({
  id: '/cerita',
  path: '/cerita',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TensesTenseRoute = TensesTenseRouteImport.update({
  id: '/tenses_/$tense',
  path: '/tenses/$tense',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz_/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const CeritaSlugRoute = CeritaSlugRouteImport.update({
  id: '/cerita_/$slug',
  path: '/cerita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerita': typeof CeritaRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenses': typeof TensesRoute
  '/cerita/$slug': typeof CeritaSlugRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/tenses/$tense': typeof TensesTenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerita': typeof CeritaRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenses': typeof TensesRoute
  '/cerita/$slug': typeof CeritaSlugRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/tenses/$tense': typeof TensesTenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerita': typeof CeritaRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenses': typeof TensesRoute
  '/cerita_/$slug': typeof CeritaSlugRoute
  '/quiz_/$quizId': typeof QuizQuizIdRoute
  '/tenses_/$tense': typeof TensesTenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cerita'
    | '/progress'
    | '/quiz'
    | '/reference'
    | '/sitemap.xml'
    | '/tenses'
    | '/cerita/$slug'
    | '/quiz/$quizId'
    | '/tenses/$tense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cerita'
    | '/progress'
    | '/quiz'
    | '/reference'
    | '/sitemap.xml'
    | '/tenses'
    | '/cerita/$slug'
    | '/quiz/$quizId'
    | '/tenses/$tense'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cerita'
    | '/progress'
    | '/quiz'
    | '/reference'
    | '/sitemap.xml'
    | '/tenses'
    | '/cerita_/$slug'
    | '/quiz_/$quizId'
    | '/tenses_/$tense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CeritaRoute: typeof CeritaRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRoute
  ReferenceRoute: typeof ReferenceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TensesRoute: typeof TensesRoute
  CeritaSlugRoute: typeof CeritaSlugRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  TensesTenseRoute: typeof TensesTenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenses': {
      id: '/tenses'
      path: '/tenses'
      fullPath: '/tenses'
      preLoaderRoute: typeof TensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerita': {
      id: '/cerita'
      path: '/cerita'
      fullPath: '/cerita'
      preLoaderRoute: typeof CeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenses_/$tense': {
      id: '/tenses_/$tense'
      path: '/tenses/$tense'
      fullPath: '/tenses/$tense'
      preLoaderRoute: typeof TensesTenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz_/$quizId': {
      id: '/quiz_/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerita_/$slug': {
      id: '/cerita_/$slug'
      path: '/cerita/$slug'
      fullPath: '/cerita/$slug'
      preLoaderRoute: typeof CeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CeritaRoute: CeritaRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRoute,
  ReferenceRoute: ReferenceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TensesRoute: TensesRoute,
  CeritaSlugRoute: CeritaSlugRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  TensesTenseRoute: TensesTenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
